-- Compatibility wrapper.
-- Use the canonical Supabase bootstrap script at:
--   supabase/schema.sql
--
-- Open Supabase SQL Editor, paste the full contents of supabase/schema.sql,
-- select Primary Database, role postgres, then click Run.
