apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rfc-backend-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: rfc-backend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rfc-watford-prod/app
