apiVersion: v1
kind: Service
metadata:
  name: rfc-frontend
  labels:
    app.kubernetes.io/name: rfc-frontend
    app.kubernetes.io/part-of: rfc-watford
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rfc-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
