apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rfc-backend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rfc-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rfc-frontend
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rfc-frontend
