apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rfc-staging

resources:
  - ../../base

images:
  - name: rfc-backend
    newName: ghcr.io/rfc-watford/rfc-backend
    newTag: staging
  - name: rfc-frontend
    newName: ghcr.io/rfc-watford/rfc-frontend
    newTag: staging

patches:
  - path: configmap-backend.patch.yaml
  - path: external-secret-backend.patch.yaml
  - path: ingress.patch.yaml
  - path: replicas.patch.yaml
  - path: hpa.patch.yaml
